exproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mqapp.urls")),
]

mqapp/urls.py
from django.urls import path
from mqapp import views

app_name = "mqapp"

urlpatterns = [
    path("", views.TopView, name="top"),
    path("home/", views.HomeView, name="home"),
    path("login/", views.Login, name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signin/", views.SignIn, name="signin"),
    path("edit/<str:En>", views.EditView, name="edit"),
    path("play/<str:En>/<str:Ja>", views.PlayView, name="play"),
    path("play_m/<str:En>/<str:Ja>", views.PlayView, name="play_m"),
    path("net_post/", views.NetPost, name="net_post"),
    path("edit_n/<str:En>", views.Edit_nView, name="edit_n"),
    path("play_n/<str:En>/<str:Ja>", views.PlayView_n, name="play_n"),
    path("play_m_n/<str:En>/<str:Ja>", views.PlayView_n, name="play_m_n"),
    path("ajax-list/",views.Ajax_List, name="ajax-list"),
]

mqapp/models.py
from django.db import models
from django_mysql.models import ListCharField

class data(models.Model):
    username = models.CharField(max_length=20)
    list_data = models.CharField(max_length=400, default='')
    type_data = models.CharField(max_length=400,default='')
    title = ListCharField(
        base_field=models.CharField(max_length=20),
        size=200,
        max_length=(200 * 21),
    )
    text_data = ListCharField(
        base_field=models.CharField(max_length=20000),
        size=200,
        max_length=(200 * 20001),
    )
    id_data = ListCharField(
        base_field = models.CharField(max_length=5),
        size=200,
        max_length=(200 * 6)
    )
    post_data = ListCharField(
        base_field = models.CharField(max_length=10),
        size=200,
        max_length=(200 * 11)
    )

class post_data(models.Model):
    username = models.CharField(max_length=20)
    title = models.CharField(max_length=20)
    text_data = models.CharField(max_length=20000)
    id_data = models.CharField(max_length=5)
    type_data = models.CharField(max_length=1, default='')


mqapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from mqapp.models import data

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class NewCreate(forms.ModelForm):
    class Meta:
        model = data
        exclude = ('username','text_data','id_data', 'post_data', 'list_data')

mqapp/views.py
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from . import forms

from mqapp.models import data,post_data

import random, string


def TopView(request):
    if request.method == 'POST':
        if 'un' in request.POST:
            name = request.POST['un']
            if data.objects.filter(username = name).exists() == True:
                user_data = data.objects.filter(username = name)
                user_data.delete()
                user_data2 = User.objects.filter(username = name)
                user_data2.delete()
    if request.user.is_authenticated == True:
        return HomeView(request)
    else:
        return render(request, 'mqapp/top.html',{'path':'top'})

def HomeView(request):
    username = str(request.user)
    form = forms.NewCreate()

    if data.objects.filter(username = username).exists() == False:
        user_data = data.objects.create(username = username, title = [], text_data = [], id_data = [], post_data = [], list_data = '', type_data = '')
    else:
        user_data = data.objects.get(username = username)
        if len(user_data.title) > 0 and len(user_data.list_data) == 0:
            for i in range(len(user_data.title)):
                user_data.list_data += str(i)+','
        if len(user_data.title) > 0 and len(user_data.type_data) == 0:
            for i in range(len(user_data.title)):
                user_data.type_data += '1,'
    user_data.save()
    
    if request.method == 'POST':
        if 'title' in request.POST:
            tt = request.POST['title']
            if tt != '':
                Flag = False
                for i in user_data.title:
                    if i == tt:
                        Flag = True
                if Flag == False:
                    user_data.title.append(tt)
                    user_data.text_data.append('null')
                    while(True):
                        id_text = ''.join([random.choice(string.ascii_letters + string.digits) for i in range(5)])
                        flag = False
                        for i in data.objects.all():
                            for ii in i.id_data:
                                if id_text == ii:
                                    flag = True
                        if flag == False:
                            break
                    user_data.id_data.append(id_text)
                    user_data.post_data.append('false')
                    user_data.type_data += '1,'
                    if user_data.list_data == '':
                        ire = 0
                        user_data.list_data += str(ire)
                    else:
                        ire = int(max(user_data.list_data)) + 1
                        user_data.list_data += ','+str(ire)
                    
        elif 'ds' in request.POST:
            tt = request.POST['ds']
            if tt != '':
                idx = user_data.title.index(tt)
                if user_data.post_data[idx] == 'true':
                    P_data = post_data.objects.filter(id_data = user_data.id_data[idx])
                    P_data.delete()
                user_data.title.pop(idx)
                user_data.text_data.pop(idx)
                user_data.id_data.pop(idx)
                user_data.post_data.pop(idx)
                a = user_data.type_data.split(',')
                a.pop(idx)
                a = ','.join(a)
                user_data.type_data = a
                ll = user_data.list_data.split(',')
                atai = ll[idx]
                ll.pop(idx)
                for i in range(len(ll)):
                    if int(ll[i]) > int(atai):
                       ll[i] = str(int(ll[i]) - 1)
                ll = ','.join(ll)
                
                user_data.list_data = ll
        elif 'duser' in request.POST and 'did' in request.POST:
            duser = request.POST['duser']
            did = request.POST['did']
            if duser != '' and data.objects.filter(username = duser).exists() and did != '':
                dlu = data.objects.get(username = duser)
                idx = dlu.id_data.index(did)
                user_data.title.append(dlu.title[idx]+'(ダウンロード)')
                user_data.text_data.append(dlu.text_data[idx])
                user_data.post_data.append('no')
                user_data.type_data += dlu.type_data.split(',')[idx]
                if user_data.list_data == '':
                    ire = 0
                    user_data.list_data += str(ire)
                else:
                    ire = int(max(user_data.list_data)) + 1
                    user_data.list_data += ','+str(ire)
                while(True):
                    id_text = ''.join([random.choice(string.ascii_letters + string.digits) for i in range(5)])
                    flag = False
                    for i in user_data.id_data:
                        if i == id_text:
                            Flag = True
                    if flag == False:
                        break
                user_data.id_data.append(id_text)
    user_data.save()
    ul = user_data.title
    type_data = user_data.type_data
    import os
    cwd = os.getcwd()
    print(cwd)
    return render(request, 'mqapp/home.html', {'form':form, 'ul': ul, 'path':'home', 'lc':user_data.list_data, 'type':type_data, 'cwd':cwd})

from django.contrib.auth import authenticate, login

def Login(request):
    form = forms.LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HomeView(request)
        else:
            return render(request, 'mqapp/login.html', {'form':form, 'ms': '※そのユーザーは存在しません。'})
    return render(request, 'mqapp/login.html', {'form':form, 'ms':'', 'path':'login'})

class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = "mqapp/login.html"

def SignIn(request):
    ms = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/home')
        for i in User.objects.all():
            if request.POST['username'] == str(i):
                ms = '※この名前はすでに使われています'
    else:
        form = UserCreationForm()
    return render(request, 'mqapp/signin.html', {'form': form, 'ms':ms, 'path':'signin'})

def EditView(request, En):
    user_data = data.objects.get(username = str(request.user))
    idx = user_data.title.index(En)

    if request.method == 'POST':
        if 'data_text' in request.POST:
            user_data.text_data[idx] = str(request.POST['data_text'])
            user_data.save()
        if 'h_title' in request.POST:
            tt = str(request.POST['h_title'])
            a = user_data.type_data.split(",")
            if 'radio1' in request.POST:
                a[idx] = '1'
            elif 'radio2' in request.POST:
                a[idx] = '2'
            elif 'radio3' in request.POST:
                a[idx] = '3'
            user_data.type_data = ','.join(a)
            
            user_data.title[idx] = tt
            user_data.save()
            En = tt
    type_data = user_data.type_data.split(',')[idx]
    pd = user_data.post_data[idx]
    tab = user_data.text_data[idx]
    id_text = user_data.id_data[idx]
    
    if request.method == 'POST':
        if 'pst' in request.POST:
            if request.POST['pst'] == 'ok':
                if post_data.objects.filter(id_data = user_data.id_data[idx]).exists() == False:
                    P_data = post_data.objects.create(username = request.user, title = user_data.title[idx], text_data = user_data.text_data[idx], id_data = user_data.id_data[idx], type_data = user_data.type_data.split(',')[idx])
                else:
                    P_data = post_data.objects.get(id_data = user_data.id_data[idx])
                    P_data.title = user_data.title[idx]
                    P_data.text_data = user_data.text_data[idx]
                    P_data.type_data = user_data.type_data.split(',')[idx]
                    P_data.save()
                pd = 'true'
                user_data.post_data[idx] = 'true'
                user_data.save()
                return HomeView(request)
            
            if request.POST['pst'] == 'no':
                P_data = post_data.objects.filter(id_data = user_data.id_data[idx])
                P_data.delete()
                user_data.post_data[idx] = 'false'
                user_data.save()
                pd = 'false'
                    
    return render(request, 'mqapp/edit.html', {'en':En, 'tab': tab, 'id_text': id_text, 'path':'edit', 'pf':pd, 'type':type_data})

def PlayView(request, En, Ja):
    user_data = data.objects.get(username = str(request.user))
    idx = user_data.title.index(En)
    tab = user_data.text_data[idx]
    if request.method == 'POST':
        if 'miss' in request.POST:
            text_d = request.POST['miss']
            title_d = request.POST['title']
            Flag = False
            for i in user_data.title:
                if i == title_d:
                    Flag = True
            if Flag == False:
                user_data.title.append(title_d)

mqapp/templates/mqapp/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/css/drawer.min.css">

    <title>{% block title %}{% endblock %}</title>

    <style>
      body {
         -webkit-text-size-adjust: 100%;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand mr-auto" href="/" style="font-size: 1.9vmax;white-space: nowrap;">問題集作成サイト</a>
            {% if path == 'edit' %}
            <button type="button" class="btn btn-secondary mx-1" Onclick="Open();">設定</button>
            {% endif %}
            {% if path == 'home' %}
            <a class="navbar-brand text-light" href="/net_post/" style="font-size: 1.4vmax;white-space: nowrap;">みんなの問題集</a>
            {% endif %}
            {% if request.user.is_authenticated  %}
            <ul class="dropdown">
              <button class="dropdown-toggle btn btn-info float-right" data-toggle="dropdown">{{ request.user }}</button>
                  <ul class="dropdown-menu">
                    <button type="button" class="btn btn-primary my-1" data-toggle="modal" data-target="#DlModal" style="white-space: nowrap;">ダウンロード</button>
                    <button class="btn btn-danger my-1" data-toggle="modal" data-target="#AdModal" style="white-space: nowrap;" onclick="Dn();">アカウント削除</button>
                    <a href="{% url 'mqapp:logout' %}" class="btn btn-success my-1" style="white-space: nowrap;">ログアウト</a>
                  </ul>
            </ul>
            {% endif %}
            {% if request.path == '/signin/' %}
            <a href="{% url 'mqapp:login' %}" class="btn btn-primary" style="font-size: 1vmax;white-space: nowrap;">ログイン</a>
            {% endif %}
        </div>
      </nav>

    <!-- ダウンロードダイアログ -->
<div class="modal fade" id="DlModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <form action="/home/" method="POST">
    {% csrf_token %}
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" >ダウンロード</h4>
      </div>
      <div class="modal-body">
        <h5>相手のユーザーネーム</h5>
        <input type="text" name="duser" maxlength="100" id="duser" class="form-control">
        <h5>id</h5>
        <input type="text" name="did" maxlength="5" id="did" class="form-control">
      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-success" >ダウンロード</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">閉じる</button>
      </div>
    </div>
    </form>
  </div>
</div>

<!-- アカウント削除 -->
<div class="modal fade" id="AdModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
  <form action="/" method="POST">
  {% csrf_token %}
  <input type="text" name = "un" id="un" value= {{ request.user }}>
  <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title" >本当にアカウントを削除しますか？</h4>
      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-danger" >アカウント削除</button>
          <button class="btn btn-info" data-dismiss="modal">閉じる</button>
      </div>
  </div>
  </form>
  </div>
</div>

<script>
  let un = document.getElementById('un');
  un.style.display = "none";
</script>
<script src="https://code.jquery.com/jquery-3.5.0.min.js"integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/js/drawer.min.js"></script>


    {% block content %}{% endblock %}
    
  </body>
</html>

mqapp/templates/mqapp/home.html
{% extends "mqapp/base.html" %}
{% block title %}ホーム{% endblock %}

{% block content %}
<div class="container">
    <h1>{{cwd}}</h1>
    <div class="card mt-3 mx-auto" style="width: 60vw;">
        <div class="card-header">
            <div class="row">
                <div class="col-md-10">
                    <h4 style="font-size: 2vmax;white-space: nowrap;">作成した問題集</h4>
                </div>
                <div class="col-md-2">
                    <button type="button" style=" padding-left:4px;padding-right:4px; white-space: nowrap;" class="btn btn-primary float-right" data-toggle="modal" data-target="#CreateModal">新規作成</button>
                </div>
            </div>
        </div>
        <div class="card-body bg-light" id="oya">
                {% for bt in ul %}
                <div class="card my-4" draggable="true" id="card{{ forloop.counter0 }}">
                    <div class="card-body" id = "child">
                        <div class="row" id = "child">
                            <div class="col-md-12 col-sm-12" id = "child">
                                <h6 style="font-size: 1.7vmax;" id = "child">{{ bt }}</h6>
                            </div>
                            <div class = "col-md-12 col-sm-12" id = "child">
                                <ul class="dropdown" id = "child">
                                    <button  id = "child" class="dropdown-toggle btn btn-outline-primary float-right" data-toggle="dropdown">メニュー</button>
                                        <ul class="dropdown-menu">
                                            <a class="text-info mx-1" href="/play/{{ bt }}/t" id="buta{{forloop.counter0}}">記述</a>
                                            <a class="text-info mx-1" href="/play/{{ bt }}/m" id="kame{{forloop.counter0}}">〇✕</a>
                                            <a href="/edit/{{ bt }}" class="btn btn-success">編集</a>
                                            <button class="btn btn-danger" data-toggle="modal" data-target="#DeleteModal" onclick="Send(this);">削除</button>
                                        </ul>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
        </div>
        <div class="card-body bg-light" id="oya2"></div>
    </div>
</div>

<!-- 新規作成ダイアログ -->
<div class="modal fade" id="CreateModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <form action="/home/" method="POST">
        {% csrf_token %}
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >問題集新規作成</h4>
            </div>
            <div class="modal-body">
                <h4>タイトル</h4>
                <input type="text" name="title" maxlength="20" required id="id_title" id="title" class="form-control">
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success" >新規作成</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">閉じる</button>
            </div>
        </div>
        </form>
    </div>
</div>

<!--　削除ダイアログ　-->
<form action="/home/" method="POST">
{% csrf_token %}
<input type="text" id="ds" name="ds">
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="text"></h4>
            </div>
            <div class="modal-body">
                <button type="submit" class="btn btn-danger" >削除</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">戻る</button>
            </div>
        </div>
    </div>
</div>
</form>

<form id="fr" action="" method="POST">
    {% csrf_token %}
    <input type="text" id="kore" required>
    <button type="submit" id="fr2"></button>
</form>

<p id="lcc">{{ lc }}</p>
<p id="ttt">{{ type }}</p>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    document.getElementById('fr2').style.display = 'none';
    document.getElementById('ds').style.display = 'none';
    document.getElementById('kore').style.display = 'none';
    ttt = document.getElementById('ttt');
    ttt.style.display = 'none';
    ttt = ttt.textContent.split(',');

    let lc = document.getElementById('lcc');
    let lcn = lc.textContent.split(',');
    lc.style.display = 'none';

    list_card = [];
    let oya = document.getElementById('oya');
    let oya2 = document.getElementById('oya2');

    if(oya.childElementCount > 0){
        for(let i = 0; i < oya.childElementCount; i++){
            if(ttt[i] == '2'){
                document.getElementById('kame'+String(i)).style.display = 'none';
            }
            else if(ttt[i] == '3'){
                document.getElementById('buta'+String(i)).style.display = 'none';
            }
        }
    }

    let list_t = [];
    if(oya.childElementCount > 0 && lc.textContent != "," && lc.textContent != ""){
        for(let i = 0; i < oya.childElementCount; i++ ){
            list_card.push([oya.children[i].id,lcn[i]]);
        }
        var t = oya.children;
        for(let i = 0; i < oya.childElementCount; i++){
            list_t.push(oya.children[i].id);
        }
        let vv = oya.childElementCount;
        let div_list = [];
        for(let ia = 0; ia < vv; ia++){
            let i3 = 0;
            for(let ii = 0; ii < vv; ii++){
                if(list_card[ii][1] == ia){
                    div_list.push(t[ii]);
                }
            }
        }
        
        for(let i = 0; i < vv ; i++){
            oya2.appendChild(div_list[i]);
        }
        oya.style.display = 'none';
    }
    let doo = '2';
    let doo2 = '';
    function Change(){
        let oya = document.getElementById('oya'+doo);
        let oya2 = document.getElementById('oya' + doo2);
        oya2.style.display = 'block';
        if(doo == 2){
            doo = '';
            doo2 = '2';
        }
        else{
            doo = '2';
            doo2 = '';
        }
        if(oya.childElementCount > 0){
            var t = [];
            for(let i = 0; i < list_t.length; i++){
                t.push(document.getElementById(list_t[i]));
            }
            let vv = oya.childElementCount;
            let div_list = [];
            for(let ia = 0; ia < vv; ia++){
                let i3 = 0;
                for(let ii = 0; ii < vv; ii++){
                    if(list_card[ii][1] == ia){
                        div_list.push(t[ii]);
                    }
                }
            }
            
            for(let i = 0; i < vv ; i++){
                oya2.appendChild(div_list[i]);
            }
            oya.style.display = 'none';
        }
    }
    
    function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

    $('#fr').on('submit', function(e) {
        e.preventDefault();
        var csrf_token = getCookie("csrftoken");
        $.ajax({
            'url': '{% url "mqapp:ajax-list" %}',
            'type': 'POST',
            'data': {
                'list': $('#kore').val(),
            },
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            },
            'dataType': 'json',
            
        });
    });

    function Send(element){
        let vv = element.parentElement.parentElement.parentElement.parentElement.children[0].children[0].textContent;
        document.getElementById('text').innerHTML = vv + 'を本当に削除しますか？';
        document.getElementById('ds').value = vv;
    }

    // ドラッグしている要素を格納する変数
    let drag_item;
    
    // ドラッグが開始された時
    document.addEventListener('dragstart', (event) => {
      drag_item = event.target;
      event.target.style.opacity = 0.6;
    });
    
    // ドラッグが終了した時
    document.addEventListener('dragend', (event) => {
      event.target.style.opacity = 1;
    });

    document.addEventListener('dragover', (event) =>{
      event.preventDefault();
    });
    
    // ドロップ時の処理
    window.addEventListener('drop', (event) => {
        let e = event.target;
      while(true){
        if(e.id == 'child'){
            e = e.parentElement;
        }
        else{
            break;
        }
      }
      if((e.id).includes('card')){
        var e_1 = document.getElementById(drag_item.id);
        var e_2 = document.getElementById(e.id);
        let ted = 0, ted2 = 0;
        let td = 0, td2 = 0;
        for(let i = 0; i < list_card.length; i++){
            if(list_card[i][0] == drag_item.id){
                ted = list_card[i][1];
                td = i;
            }
            if(list_card[i][0] == e.id){
                ted2 = list_card[i][1];
                td2 = i;
            }
        }
        let nol = [];
        if(ted > ted2){
            for(let i = ted2; i < ted; i++){
                var target = list_card.filter( e => e[1] === String(i) );
                nol.push(parseInt(target[0][0].split('card')[1]))
            }
            for(let i = 0; i < nol.length; i++){
                let suti = parseInt(list_card[nol[i]][1]);
                list_card[nol[i]][1] = String(suti + 1);
            }
        }
        else{
            for(let i = ted2; i > ted; i--){
                var target = list_card.filter( e => e[1] === String(i) );
                nol.push(parseInt(target[0][0].split('card')[1]))
            }
            for(let i = 0; i < nol.length; i++){
                let suti = parseInt(list_card[nol[i]][1]);
                list_card[nol[i]][1] = String(suti - 1);
            }
        }
        list_card[td][1] = ted2;

        let ii2 = list_card.flat();
        for(let ii3 = 0; ii3 < list_card.length; ii3++){
            ii2.splice(ii3,1);
        }
        let imadake = ii2.join(',');
        
        document.getElementById('kore').value = imadake;
        document.getElementById("fr2").click();

        Change();
      }
      
      event.preventDefault();
      drag_item = null;
    }, false);
</script>

{% endblock %}

mqapp/templates/mqapp/login.html
{% extends "mqapp/base.html" %}
{% block title %}ログイン{% endblock %}

{% block content %}

<div class="container">
    <form action="" method="POST" class="from-group">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="card mt-3 mx-auto" style="width: 50%;">
        <div class="card-header">
            ログイン
        </div>
        <div class="card-body">
            <p>{{ ms }}</p>
            {% for field in form %}
            {{ field.label }}
            <br>
            {{ field }}
            <br>
            {{ field.error }}
            {% endfor %}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-outline-primary">ログイン</button>
        </div>
      </div>
    </form>
</div>

{% endblock %}

mqapp/templates/mqapp/top.html
{% extends "mqapp/base.html" %}

{% block title %}トップ{% endblock %}

{% block content %}
<div class="container">
    <div class="card mt-3 mx-auto" style="width: 50%;">
        <div class="card-header">
            アカウント
        </div>
        <div class="card-body">
          <p class="card-text">このサイトを利用するにはサインアップすでにあるアカウントにログインする必要があります</p>
        </div>
        <div class="card-footer">
            <a href="{% url 'mqapp:login' %}" class="btn btn-outline-primary">ログイン</a>
            <a href="{% url 'mqapp:signin' %}" class="btn btn-outline-primary">サインアップ</a>
        </div>
      </div>
</div>
{% endblock %}